/**
 * Lista de alimentos do Bocado de Nutrição (definida pelo nutricionista, 8
 * grupos) com a REGRA DE BUSCA de cada item na TACO. A regra só procura
 * palavras na descrição oficial — nenhum valor nutricional é atribuído aqui.
 *
 * - `head`: primeiro trecho da descrição TACO (antes da 1ª vírgula), já
 *   normalizado ("frango", "carne", "porco", "ovo"…).
 * - `all`: palavras que precisam aparecer (tolerando plural); `none`: excluem.
 * - `sinonimo`: a busca usa outro nome da TACO (ex.: aipim → mandioca) — o
 *   resultado NUNCA vira "encontrado" sozinho; vai para revisão.
 * - `revisar`: motivo para mandar à revisão mesmo com um único candidato.
 * - `numeros`: candidatos indicados por número (só para defeito da planilha).
 * - `foraDaTaco`: produto de marca/suplemento/industrializado; sem candidato
 *   na TACO, fica separado e sem valores.
 */
export interface BocadoFoodRule {
  nome: string;
  head?: string | string[];
  all?: string[];
  none?: string[];
  sinonimo?: string;
  revisar?: string;
  numeros?: number[];
  foraDaTaco?: boolean;
  obs?: string;
}

export interface BocadoFoodGroup {
  grupo: string;
  itens: BocadoFoodRule[];
}

const syn = (nome: string, rule: Omit<BocadoFoodRule, 'nome' | 'sinonimo'>, sinonimo: string): BocadoFoodRule => ({ nome, ...rule, sinonimo });
const fora = (nome: string, obs?: string): BocadoFoodRule => ({ nome, foraDaTaco: true, obs });

export const BOCADO_FOOD_LIST: BocadoFoodGroup[] = [
  {
    grupo: '1. Proteínas',
    itens: [
      { nome: 'Peito de frango', head: 'frango', all: ['peito'] },
      { nome: 'Coxa de frango', head: 'frango', all: ['coxa'] },
      { nome: 'Sobrecoxa', head: 'frango', all: ['sobrecoxa'] },
      { nome: 'Frango desfiado', head: 'frango', all: ['desfiado'], obs: 'A TACO não tem frango desfiado; é preparação do peito ou da coxa.' },
      { nome: 'Patinho', head: 'carne', all: ['patinho'] },
      { nome: 'Coxão mole', head: 'carne', all: ['coxao', 'mole'] },
      { nome: 'Coxão duro', head: 'carne', all: ['coxao', 'duro'] },
      { nome: 'Alcatra', head: 'carne', all: ['alcatra'] },
      { nome: 'Contrafilé', head: 'carne', all: ['contra', 'file'] },
      { nome: 'Filé mignon', head: 'carne', all: ['mingnon'], obs: 'Na TACO a grafia é "filé mingnon".' },
      { nome: 'Acém', head: 'carne', all: ['acem'] },
      { nome: 'Músculo', head: 'carne', all: ['musculo'] },
      syn('Carne moída magra', { head: 'carne', all: ['moido'] }, 'A TACO só tem acém moído; não distingue magra de comum.'),
      syn('Carne moída comum', { head: 'carne', all: ['moido'] }, 'A TACO só tem acém moído; não distingue magra de comum.'),
      { nome: 'Lagarto', head: 'carne', all: ['lagarto'] },
      { nome: 'Fígado bovino', head: 'carne', all: ['bovina', 'figado'] },
      syn('Lombo suíno', { head: 'porco', all: ['lombo'] }, 'Na TACO, suíno aparece como "Porco".'),
      syn('Pernil suíno', { head: 'porco', all: ['pernil'] }, 'Na TACO, suíno aparece como "Porco".'),
      { nome: 'Filé suíno', head: 'porco', all: ['file'] },
      { nome: 'Tilápia', head: 'tilapia' },
      { nome: 'Sardinha', head: 'sardinha' },
      { nome: 'Atum', head: 'atum' },
      { nome: 'Salmão', head: 'salmao' },
      { nome: 'Merluza', head: 'merluza' },
      { nome: 'Pescada', head: 'pescada' },
      { nome: 'Bacalhau', head: 'bacalhau' },
      { nome: 'Camarão', head: 'camarao' },
      { nome: 'Ovos', head: 'ovo', all: ['galinha', 'inteiro'] },
      { nome: 'Clara de ovo', head: 'ovo', all: ['clara'] },
      { nome: 'Ovo de codorna', head: 'ovo', all: ['codorna'] },
      fora('Whey protein', 'Suplemento: valores dependem do rótulo.'),
      fora('Caseína', 'Suplemento: valores dependem do rótulo.'),
      fora('Proteína vegetal', 'Suplemento/produto: valores dependem do rótulo.'),
      { nome: 'Tofu', all: ['tofu'] },
      fora('Tempeh', 'Não consta na TACO.'),
    ],
  },
  {
    grupo: '2. Carboidratos',
    itens: [
      syn('Arroz branco', { head: 'arroz', all: ['tipo'] }, 'Na TACO, arroz branco aparece como "tipo 1" e "tipo 2".'),
      { nome: 'Arroz integral', head: 'arroz', all: ['integral'] },
      { nome: 'Arroz parboilizado', head: 'arroz', all: ['parboilizado'] },
      { nome: 'Arroz vermelho', head: 'arroz', all: ['vermelho'] },
      { nome: 'Arroz negro', head: 'arroz', all: ['negro'] },
      { nome: 'Feijão carioca', head: 'feijao', all: ['carioca'] },
      { nome: 'Feijão preto', head: 'feijao', all: ['preto'] },
      { nome: 'Feijão vermelho', head: 'feijao', all: ['vermelho'], obs: 'A TACO tem feijão roxo, rajado, rosinha e jalo, mas não "vermelho".' },
      { nome: 'Lentilha', head: 'lentilha' },
      { nome: 'Grão-de-bico', head: 'grao de bico', obs: 'A TACO só tem o grão-de-bico cru.' },
      { nome: 'Ervilha', head: 'ervilha' },
      { nome: 'Quinoa', head: 'quinoa' },
      { nome: 'Aveia', head: 'aveia' },
      { nome: 'Farinha de aveia', head: 'farinha', all: ['aveia'] },
      { nome: 'Tapioca', head: 'tapioca', revisar: 'A TACO só tem "Tapioca, com manteiga" (preparação com manteiga).' },
      syn('Goma de tapioca', { head: ['fecula', 'polvilho'] }, 'Goma de tapioca corresponde a fécula/polvilho de mandioca na TACO.'),
      { nome: 'Cuscuz', head: 'cuscuz' },
      { nome: 'Milho', head: 'milho' },
      { nome: 'Fubá', all: ['fuba'] },
      { nome: 'Macarrão', head: 'macarrao' },
      { nome: 'Macarrão integral', head: 'macarrao', all: ['integral'] },
      { nome: 'Batata inglesa', head: 'batata', all: ['inglesa'] },
      { nome: 'Batata-doce', head: 'batata', all: ['doce'] },
      { nome: 'Batata-baroa/mandioquinha', head: 'batata', all: ['baroa'] },
      { nome: 'Mandioca', head: 'mandioca' },
      syn('Aipim', { head: 'mandioca' }, 'Aipim = mandioca na TACO.'),
      { nome: 'Inhame', head: 'inhame', obs: 'A TACO só tem o inhame cru.' },
      { nome: 'Cará', head: 'cara' },
      { nome: 'Abóbora', head: 'abobora' },
      { nome: 'Pão francês', head: 'pao', all: ['frances'] },
      { nome: 'Pão integral', head: 'pao', all: ['integral'] },
      { nome: 'Pão de forma', head: 'pao', all: ['forma'] },
      { nome: 'Pão de centeio', head: 'pao', all: ['centeio'], obs: 'A TACO tem farinha de centeio, mas não o pão.' },
      fora('Wrap', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Rap10', 'Produto de marca: valores dependem do rótulo.'),
      { nome: 'Torrada', head: 'torrada' },
      fora('Granola', 'Produto industrializado: valores dependem do rótulo.'),
    ],
  },
  {
    grupo: '3. Frutas',
    itens: [
      { nome: 'Banana prata', head: 'banana', all: ['prata'] },
      { nome: 'Banana nanica', head: 'banana', all: ['nanica'] },
      { nome: 'Maçã', head: 'maca' },
      { nome: 'Pera', head: 'pera' },
      { nome: 'Laranja', head: 'laranja' },
      { nome: 'Tangerina', head: 'tangerina' },
      { nome: 'Mamão', head: 'mamao' },
      { nome: 'Melão', head: 'melao' },
      { nome: 'Melancia', head: 'melancia' },
      { nome: 'Abacaxi', head: 'abacaxi' },
      { nome: 'Manga', head: 'manga' },
      { nome: 'Uva', head: 'uva' },
      { nome: 'Morango', head: 'morango' },
      { nome: 'Kiwi', head: 'kiwi' },
      { nome: 'Mirtilo', head: 'mirtilo' },
      { nome: 'Maracujá', head: 'maracuja' },
      { nome: 'Goiaba', head: 'goiaba' },
      { nome: 'Acerola', head: 'acerola' },
      { nome: 'Caju', head: 'caju' },
      { nome: 'Caqui', head: 'caqui' },
      { nome: 'Pêssego', head: 'pessego' },
      { nome: 'Ameixa', head: 'ameixa' },
      { nome: 'Figo', head: 'figo' },
      { nome: 'Abacate', head: 'abacate' },
      { nome: 'Coco', head: 'coco' },
      { nome: 'Limão', head: 'limao' },
    ],
  },
  {
    grupo: '4. Verduras e legumes',
    itens: [
      { nome: 'Alface', head: 'alface' },
      { nome: 'Rúcula', head: 'rucula' },
      { nome: 'Agrião', head: 'agriao' },
      { nome: 'Couve', head: 'couve' },
      { nome: 'Espinafre', head: 'espinafre' },
      { nome: 'Acelga', head: 'acelga' },
      { nome: 'Repolho', head: 'repolho' },
      { nome: 'Brócolis', head: 'brocolis' },
      { nome: 'Couve-flor', head: 'couve flor' },
      { nome: 'Cenoura', head: 'cenoura' },
      { nome: 'Beterraba', head: 'beterraba' },
      { nome: 'Abobrinha', head: 'abobrinha' },
      { nome: 'Berinjela', head: 'berinjela' },
      { nome: 'Chuchu', head: 'chuchu' },
      { nome: 'Pepino', head: 'pepino' },
      { nome: 'Tomate', head: 'tomate' },
      { nome: 'Vagem', head: 'vagem' },
      { nome: 'Quiabo', head: 'quiabo' },
      { nome: 'Pimentão', head: 'pimentao' },
      { nome: 'Cebola', head: 'cebola' },
      { nome: 'Alho', head: 'alho' },
      { nome: 'Milho', head: 'milho' },
      { nome: 'Ervilha', head: 'ervilha' },
      { nome: 'Aspargos', head: 'aspargo' },
      { nome: 'Cogumelos', head: 'cogumelo' },
      { nome: 'Palmito', head: 'palmito' },
    ],
  },
  {
    grupo: '5. Gorduras e oleaginosas',
    itens: [
      { nome: 'Azeite de oliva', head: 'azeite', all: ['oliva'] },
      { nome: 'Óleo de coco', head: 'oleo', all: ['coco'] },
      { nome: 'Óleo de canola', head: 'oleo', all: ['canola'] },
      { nome: 'Manteiga', head: 'manteiga' },
      fora('Pasta de amendoim', 'Produto industrializado: valores dependem do rótulo.'),
      { nome: 'Amendoim', head: 'amendoim' },
      syn('Castanha-do-Pará', { head: 'castanha do brasil' }, 'Castanha-do-Pará aparece como "Castanha-do-Brasil" na TACO.'),
      { nome: 'Castanha de caju', head: 'castanha de caju' },
      { nome: 'Amêndoas', head: 'amendoa', obs: 'A TACO só tem amêndoa torrada e salgada.' },
      { nome: 'Nozes', head: 'noz' },
      { nome: 'Pistache', head: 'pistache' },
      { nome: 'Macadâmia', head: 'macadamia' },
      { nome: 'Semente de chia', all: ['chia'] },
      { nome: 'Linhaça', head: 'linhaca' },
      { nome: 'Gergelim', head: 'gergelim' },
      { nome: 'Semente de abóbora', all: ['semente', 'abobora'] },
      { nome: 'Tahine', all: ['tahine'] },
    ],
  },
  {
    grupo: '6. Lácteos e alternativas',
    itens: [
      { nome: 'Leite integral', head: 'leite', all: ['vaca', 'integral'] },
      { nome: 'Leite desnatado', head: 'leite', all: ['vaca', 'desnatado'] },
      { nome: 'Leite semidesnatado', head: 'leite', all: ['semidesnatado'] },
      fora('Leite zero lactose', 'Produto industrializado: valores dependem do rótulo.'),
      { nome: 'Iogurte natural', head: 'iogurte', all: ['natural'] },
      fora('Iogurte grego', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Iogurte zero lactose', 'Produto industrializado: valores dependem do rótulo.'),
      { nome: 'Kefir', all: ['kefir'], obs: 'A TACO tem "Leite, fermentado", que não é kefir.' },
      { nome: 'Queijo minas', head: 'queijo', all: ['minas'] },
      syn('Muçarela', { head: 'queijo', all: ['mozarela'] }, 'Na TACO a grafia é "mozarela".'),
      { nome: 'Cottage', all: ['cottage'] },
      { nome: 'Ricota', head: 'queijo', all: ['ricota'] },
      fora('Cream cheese', 'Produto industrializado: valores dependem do rótulo.'),
      { nome: 'Requeijão', head: 'queijo', all: ['requeijao'] },
      fora('Requeijão light', 'Produto industrializado: valores dependem do rótulo.'),
      syn('Bebida de soja', { head: 'soja', all: ['extrato', 'fluido'] }, 'Na TACO: "Soja, extrato solúvel, natural, fluido".'),
      fora('Bebida de amêndoas', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Bebida de aveia', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Bebida de coco', 'A TACO tem "Leite, de coco" (uso culinário), não a bebida.'),
    ],
  },
  {
    grupo: '7. Alimentos práticos para dieta',
    itens: [
      syn('Peito de peru', { head: 'peru' }, 'A TACO tem peru congelado (carne), não o peito de peru fatiado (frios).'),
      { nome: 'Presunto', head: 'presunto' },
      { nome: 'Atum em água', head: 'atum', all: ['agua'], obs: 'A TACO só tem atum em óleo e atum fresco.' },
      syn('Sardinha em lata', { head: 'sardinha', all: ['conserva'] }, 'Na TACO: "Sardinha, conserva em óleo".'),
      { nome: 'Frango pronto/desfiado', head: 'frango', all: ['desfiado'], obs: 'A TACO não tem frango desfiado pronto.' },
      { nome: 'Hambúrguer bovino', head: 'hamburguer', all: ['bovino'] },
      fora('Hambúrguer de frango', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Hambúrguer vegetal', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Queijo light', 'Produto industrializado: valores dependem do rótulo.'),
      { nome: 'Pão integral', head: 'pao', all: ['integral'] },
      fora('Wrap integral', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Granola sem açúcar', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Pasta de amendoim', 'Produto industrializado: valores dependem do rótulo.'),
      fora('Geleia sem açúcar', 'A TACO só tem geleia de mocotó.'),
      fora('Chocolate 70%', 'A TACO tem chocolate meio amargo, sem teor de cacau definido.'),
      { nome: 'Cacau em pó', all: ['cacau', 'po'], obs: 'A TACO tem "Cacau, cru" (fruta) e achocolatado em pó.' },
      { nome: 'Leite em pó', head: 'leite', all: ['po'] },
      fora('Whey', 'Suplemento: valores dependem do rótulo.'),
    ],
  },
  {
    grupo: '8. Alimentos brasileiros/regionais',
    itens: [
      { nome: 'Arroz carreteiro', head: 'arroz carreteiro' },
      { nome: 'Feijoada', head: 'feijoada', numeros: [540], revisar: 'Na aba principal o nº 540 está com o nome "L" (truncado); na aba de ácidos graxos o mesmo nº se chama "Feijoada".' },
      { nome: 'Farofa', all: ['farofa'], revisar: 'A TACO só tem "Mandioca, farofa, temperada".' },
      { nome: 'Polenta', head: 'polenta' },
      { nome: 'Pinhão', head: 'pinhao' },
      syn('Chimarrão', { head: 'cha', all: ['mate'] }, 'Na TACO: "Chá, mate, infusão 5%".'),
      { nome: 'Cuca', head: 'cuca' },
      { nome: 'Sagu', head: 'sagu' },
      { nome: 'Churrasco', all: ['churrasco'], obs: 'Genérico: escolha o corte (picanha, fraldinha, costela, maminha, cupim…).' },
      { nome: 'Vina', all: ['vina'], obs: 'A TACO não tem salsicha/vina.' },
      { nome: 'Linguiça', head: 'linguica' },
      { nome: 'Charque', all: ['charque'] },
      { nome: 'Carne seca', head: 'carne', all: ['seca'] },
      { nome: 'Paçoca', head: 'pacoca' },
      { nome: 'Tapioca', head: 'tapioca', revisar: 'A TACO só tem "Tapioca, com manteiga" (preparação com manteiga).' },
      syn('Cuscuz nordestino', { head: 'cuscuz', all: ['milho'] }, 'Na TACO: "Cuscuz, de milho, cozido com sal".'),
      { nome: 'Acarajé', head: 'acaraje' },
      { nome: 'Moqueca', all: ['moqueca'] },
      { nome: 'Baião de dois', head: 'baiao de dois' },
    ],
  },
];
